[package]
name = "gpug"
version = "0.1.0"
authors = ["jerlendds <oss@osintbuddy.com>"]
edition = "2021"
publish = false
repository = "https://github.com/jerlendds/gpug"
readme = "README.md"
keywords = ["gui", "gpui", "network", "graph"]
categories = ["gui"]

[lib]
name = "gpug"
path = "src/gpug.rs"
doctest = false


[dependencies]
gpui.workspace = true
rayon = "1.10"

[[example]]
name = "kitchen_sink"
path = "examples/kitchen_sink.rs"

[[example]]
name = "large_graph"
path = "examples/large_graph.rs"

[[example]]
name = "layout_benchmark"
path = "examples/layout_benchmark.rs"
